Activate form for download
andaze/LandingPages pull request #7
Opened 2023-01-04 05:29 UTC by TomoyukiHata

- [ ] フォームにバリデーションをつける
- [ ] バリデーションに引っかからなかったら資料ダウンロード可能
- [ ] ダウンロード完了メッセージをメールで通知

2023-01-05 06:21 UTC, nishidai-andaze requested changes

2023-01-05 06:21 UTC, nishidai-andaze commented on themes/generic-dx/assets/js/download.js
> +document.querySelector('.downloadButton').addEventListener('click', event => {
@TomoyukiHata submit イベントにひっかけなおす

2023-01-05 07:25 UTC, TomoyukiHata commented on themes/generic-dx/assets/js/download.js
> +document.querySelector('.downloadButton').addEventListener('click', event => {
@nishidai-andaze 修正しました

2023-01-12 06:31 UTC, nishidai-andaze approved these changes

2023-01-12 06:31 UTC, merged